using UnityEngine;
using UnityEngine.InputSystem;
using UnityEditor;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Linq;

/// <summary>
/// Editor script that generates convenience properties (WasXxxPressed/Released) 
/// for all button actions in your InputActionAsset.
/// 
/// Right-click the InputActionAsset and select "Generate Input Properties"
/// or use Tools > Generate Input Manager Properties
/// </summary>
public class InputManagerPropertyGenerator
{
    private const string GENERATED_FILE_PATH = "Assets/InputSystem/UBearInputManagerGenned.Generated.cs";
    private const string FIELD_NAME_FORMAT = "{0}ActionName";

    [MenuItem("Tools/Generate Input Manager Properties")]
    public static void GenerateProperties()
    {
        var inputActions = Selection.activeObject as InputActionAsset;
        if (inputActions == null)
        {
            EditorUtility.DisplayDialog("Error", "Select an InputActionAsset and try again", "OK");
            return;
        }

        GeneratePropertiesForAsset(inputActions);
    }

    [MenuItem("Assets/Generate Input Properties", validate = true)]
    public static bool ValidateContextMenu()
    {
        var obj = Selection.activeObject;
        return obj is InputActionAsset;
    }

    [MenuItem("Assets/Generate Input Properties")]
    public static void GeneratePropertiesFromContext()
    {
        var inputActions = Selection.activeObject as InputActionAsset;
        if (inputActions != null)
        {
            GeneratePropertiesForAsset(inputActions);
        }
    }

    static void GeneratePropertiesForAsset(InputActionAsset asset)
    {
        Debug.Log($"Generating properties for asset: {asset.name}");
        
        // Debug: Log all actions found
        int totalActions = 0;
        int buttonActions = 0;
        foreach (var map in asset.actionMaps)
        {
            foreach (var action in map.actions)
            {
                totalActions++;
                Debug.Log($"  Found action: {map.name}/{action.name} (type: {action.expectedControlType})");
                if (IsButtonLike(action))
                {
                    buttonActions++;
                }
            }
        }
        Debug.Log($"Total actions: {totalActions}, Button actions: {buttonActions}");
        
        var code = GenerateCode(asset);
        var fullPath = Path.Combine(Application.dataPath, GENERATED_FILE_PATH.Replace("Assets/", ""));
        
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
        File.WriteAllText(fullPath, code);

        AssetDatabase.Refresh();
        Debug.Log($"Generated input properties at {GENERATED_FILE_PATH}");
    }

    static string GenerateCode(InputActionAsset asset)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// AUTO-GENERATED FILE - Do not edit manually");
        sb.AppendLine("// Generated by InputManagerPropertyGenerator");
        sb.AppendLine("// To regenerate, right-click InputActionAsset and select \"Generate Input Properties\"");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.InputSystem;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("public partial class UBearInputManagerGenned : MonoBehaviour");
        sb.AppendLine("{");
        
        // Add singleton
        sb.AppendLine("    // Singleton instance");
        sb.AppendLine("    public static UBearInputManagerGenned Instance { get; private set; }");
        sb.AppendLine();
        
        // Generate InputActionAsset reference
        sb.AppendLine("    [SerializeField] InputActionAsset inputActionsAsset;");
        sb.AppendLine("    Dictionary<string, InputAction> actionCache = new Dictionary<string, InputAction>();");
        sb.AppendLine();
        
        // Add Awake for singleton
        sb.AppendLine("    void Awake()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Instance != null && Instance != this)");
        sb.AppendLine("        {");
        sb.AppendLine("            Debug.LogWarning(\"Multiple instances of UBearInputManagerGenned detected. Destroying duplicate.\");");
        sb.AppendLine("            Destroy(this);");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (inputActionsAsset == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            Debug.LogError(\"UBearInputManagerGenned: InputActionAsset is not assigned in the inspector!\");");
        sb.AppendLine("            Instance = this;");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        inputActionsAsset.Enable();");
        sb.AppendLine("        Instance = this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // Generate the necessary infrastructure (dictionaries and helper methods)
        sb.AppendLine("    // Per-frame button state tracking");
        sb.AppendLine("    protected Dictionary<string, bool> pressedThisFrame = new Dictionary<string, bool>();");
        sb.AppendLine("    protected Dictionary<string, bool> releasedThisFrame = new Dictionary<string, bool>();");
        sb.AppendLine("    protected Dictionary<string, bool> prevButtonStates = new Dictionary<string, bool>();");
        sb.AppendLine();
        
        // Add lifecycle methods
        sb.AppendLine("    void OnEnable()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (inputActionsAsset != null)");
        sb.AppendLine("            inputActionsAsset.Enable();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    void OnDisable()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (inputActionsAsset != null)");
        sb.AppendLine("            inputActionsAsset.Disable();");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // Add Update loop
        sb.AppendLine("    void Update()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (inputActionsAsset == null) return;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Clear transient frame caches");
        sb.AppendLine("        pressedThisFrame.Clear();");
        sb.AppendLine("        releasedThisFrame.Clear();");
        sb.AppendLine();
        sb.AppendLine("        // Auto-discover and update all button-like actions");
        sb.AppendLine("        foreach (var actionName in GetAllButtonActionNames())");
        sb.AppendLine("        {");
        sb.AppendLine("            UpdateButtonState(actionName);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // Add UpdateButtonState method
        sb.AppendLine("    void UpdateButtonState(string actionName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(actionName)) return;");
        sb.AppendLine();
        sb.AppendLine("        bool current = GetButtonValue(actionName);");
        sb.AppendLine("        prevButtonStates.TryGetValue(actionName, out var previous);");
        sb.AppendLine();
        sb.AppendLine("        if (current && !previous)");
        sb.AppendLine("            pressedThisFrame[actionName] = true;");
        sb.AppendLine();
        sb.AppendLine("        if (!current && previous)");
        sb.AppendLine("            releasedThisFrame[actionName] = true;");
        sb.AppendLine();
        sb.AppendLine("        prevButtonStates[actionName] = current;");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        sb.AppendLine("    /// <summary>Check if an action was pressed this frame</summary>");
        sb.AppendLine("    public bool WasPressed(string actionName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return pressedThisFrame.TryGetValue(actionName, out var v) && v;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Check if an action was released this frame</summary>");
        sb.AppendLine("    public bool WasReleased(string actionName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return releasedThisFrame.TryGetValue(actionName, out var v) && v;");
        sb.AppendLine("    }");

        var buttonActions = new List<(string mapName, string actionName)>();

        // Collect all button-like actions
        foreach (var map in asset.actionMaps)
        {
            foreach (var action in map.actions)
            {
                if (IsButtonLike(action))
                {
                    buttonActions.Add((map.name, action.name));
                }
            }
        }

        // Generate properties
        sb.AppendLine();
        sb.AppendLine("    // Generated convenience properties");
        foreach (var (mapName, actionName) in buttonActions)
        {
            var fieldName = ToFieldName(actionName);
            var propName = ToPascalCase(actionName);
            var fullActionName = $"{mapName}/{actionName}";

            sb.AppendLine();
            sb.AppendLine("    #region " + propName);
            sb.AppendLine($"    /// <summary>Was '{fullActionName}' pressed this frame?</summary>");
            sb.AppendLine($"    public bool Was{propName}Pressed => WasPressed(\"{fullActionName}\");");
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Was '{fullActionName}' released this frame?</summary>");
            sb.AppendLine($"    public bool Was{propName}Released => WasReleased(\"{fullActionName}\");");
            sb.AppendLine("    #endregion");
        }

        // Add helper methods
        sb.AppendLine();
        sb.AppendLine("    // Helper methods for button state tracking");
        sb.AppendLine("    List<string> GetAllButtonActionNames()");
        sb.AppendLine("    {");
        sb.AppendLine("        var buttonActions = new List<string>();");
        sb.AppendLine("        if (inputActionsAsset == null) return buttonActions;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var map in inputActionsAsset.actionMaps)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var action in map.actions)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (IsButtonLike(action))");
        sb.AppendLine("                {");
        sb.AppendLine("                    buttonActions.Add(map.name + \"/\" + action.name);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        return buttonActions;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    bool IsButtonLike(InputAction action)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Explicitly marked with control type");
        sb.AppendLine("        if (action.expectedControlType == \"Button\" ||");
        sb.AppendLine("            action.expectedControlType == \"Digital\")");
        sb.AppendLine("            return true;");
        sb.AppendLine();
        sb.AppendLine("        // Explicitly a value type - NOT button-like");
        sb.AppendLine("        if (action.expectedControlType == \"Vector2\" ||");
        sb.AppendLine("            action.expectedControlType == \"Axis\" ||");
        sb.AppendLine("            action.expectedControlType == \"Stick\")");
        sb.AppendLine("            return false;");
        sb.AppendLine();
        sb.AppendLine("        // No control type set - check the bindings to infer type");
        sb.AppendLine("        if (string.IsNullOrEmpty(action.expectedControlType))");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var binding in action.bindings)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (string.IsNullOrEmpty(binding.path))");
        sb.AppendLine("                    continue;");
        sb.AppendLine();
        sb.AppendLine("                string path = binding.path.ToLower();");
        sb.AppendLine();
        sb.AppendLine("                // Exclude known value types from bindings");
        sb.AppendLine("                if (path.Contains(\"<gamepad>/leftStick\") ||");
        sb.AppendLine("                    path.Contains(\"<gamepad>/rightStick\") ||");
        sb.AppendLine("                    path.Contains(\"<mouse>/delta\") ||");
        sb.AppendLine("                    path.Contains(\"/position\") ||");
        sb.AppendLine("                    path.Contains(\"/scroll\"))");
        sb.AppendLine("                    return false;");
        sb.AppendLine();
        sb.AppendLine("                // If any binding looks button-like, consider it a button action");
        sb.AppendLine("                if (path.Contains(\"button\") || ");
        sb.AppendLine("                    path.Contains(\"key\") ||");
        sb.AppendLine("                    path.Contains(\"trigger\") ||");
        sb.AppendLine("                    path.Contains(\"shoulder\"))");
        sb.AppendLine("                    return true;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // If no value-type bindings found and has bindings, likely a button");
        sb.AppendLine("            if (action.bindings.Count > 0)");
        sb.AppendLine("                return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    InputAction FindAction(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(name) || inputActionsAsset == null) return null;");
        sb.AppendLine("        if (actionCache.TryGetValue(name, out var cached)) return cached;");
        sb.AppendLine();
        sb.AppendLine("        var a = inputActionsAsset.FindAction(name, false);");
        sb.AppendLine("        if (a != null)");
        sb.AppendLine("        {");
        sb.AppendLine("            actionCache[name] = a;");
        sb.AppendLine("            return a;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var map in inputActionsAsset.actionMaps)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var action in map.actions)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (action.name == name)");
        sb.AppendLine("                {");
        sb.AppendLine("                    actionCache[name] = action;");
        sb.AppendLine("                    return action;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    bool GetButtonValue(string actionName)");
        sb.AppendLine("    {");
        sb.AppendLine("        var a = FindAction(actionName);");
        sb.AppendLine("        if (a == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            Debug.LogWarning($\"UBearInputManagerGenned: Action '{actionName}' not found in asset\");");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var f = a.ReadValue<float>();");
        sb.AppendLine("            return f > 0.5f;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch");
        sb.AppendLine("        {");
        sb.AppendLine("            return a.phase == InputActionPhase.Started || a.phase == InputActionPhase.Performed;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    static bool IsButtonLike(InputAction action)
    {
        // Explicitly marked with control type
        if (action.expectedControlType == "Button" ||
            action.expectedControlType == "Digital")
            return true;
        
        // Explicitly a value type - NOT button-like
        if (action.expectedControlType == "Vector2" ||
            action.expectedControlType == "Axis" ||
            action.expectedControlType == "Stick")
            return false;
        
        // No control type set - check the bindings to infer type
        if (string.IsNullOrEmpty(action.expectedControlType))
        {
            foreach (var binding in action.bindings)
            {
                if (string.IsNullOrEmpty(binding.path))
                    continue;
                
                string path = binding.path.ToLower();
                
                // Exclude known value types from bindings
                if (path.Contains("<gamepad>/leftStick") ||
                    path.Contains("<gamepad>/rightStick") ||
                    path.Contains("<mouse>/delta") ||
                    path.Contains("/position") ||
                    path.Contains("/scroll"))
                    return false;
                
                // If any binding looks button-like, consider it a button action
                if (path.Contains("button") || 
                    path.Contains("key") ||
                    path.Contains("trigger") ||
                    path.Contains("shoulder"))
                    return true;
            }
            
            // If no value-type bindings found and has bindings, likely a button
            if (action.bindings.Count > 0)
                return true;
        }
        
        return false;
    }

    static string ToFieldName(string name)
    {
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    static string ToPascalCase(string name)
    {
        return name; // Already in PascalCase from InputActions
    }

    static InputActionAsset FindInputActionAsset()
    {
        var guids = AssetDatabase.FindAssets("t:InputActionAsset");
        if (guids.Length == 0) return null;

        var path = AssetDatabase.GUIDToAssetPath(guids[0]);
        return AssetDatabase.LoadAssetAtPath<InputActionAsset>(path);
    }
}
